import {describe,expect,it} from 'vitest'; import {readFileSync} from 'node:fs'; import {parseBc3} from './parser';

describe('import completeness',()=>{
  it('imports a concept with an empty price as 0 and reports the defaulted price',()=>{const source='~C|R1|u|Recurso sin precio||x|0|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');expect(snapshot.items).toMatchObject([{code:'R1',kind:'resource',price:'0'}]);expect(snapshot.diagnostics).toMatchObject([{code:'missing-price-defaulted',recordTag:'C',line:1}]);});
  it('keeps a partida and its valid breakdown lines when only some children resolve',()=>{const source='~C|P1|u|Parent|1|x|0|\n~C|M1|u|Child one|2|x|0|\n~D|P1|M1\\\\1\\\\1\\\\M2\\\\1\\\\1|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');expect(snapshot.items.some(x=>x.code==='P1'&&x.kind==='partida')).toBe(true);expect(snapshot.breakdowns).toHaveLength(1);expect(snapshot.breakdowns[0]?.parent.codeKey).toBe('p1');expect(snapshot.breakdowns[0]?.line).toMatchObject({ordinal:0,component:{code:'M1',kind:'resource',unitPrice:'2'},factor:'1',yield:'1'});expect(snapshot.diagnostics.filter(x=>x.code==='unresolved-child')).toMatchObject([{parentCode:'P1',childCode:'M2',recordTag:'D',line:3}]);});
  it('still rejects a non-empty invalid price as a malformed decimal',()=>{const source='~C|R2|u|Recurso con precio no numérico|abc|x|0|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');expect(snapshot.items).toEqual([]);expect(snapshot.diagnostics).toMatchObject([{code:'malformed-decimal',recordTag:'C',line:1}]);});
  it('keeps a partida with no breakdown lines when every child is unresolved',()=>{const source='~C|P2|u|Parent|1|x|0|\n~D|P2|M9\\\\1\\\\1|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');expect(snapshot.items.some(x=>x.code==='P2')).toBe(true);expect(snapshot.breakdowns).toEqual([]);expect(snapshot.diagnostics.filter(x=>x.code==='unresolved-child')).toMatchObject([{parentCode:'P2',childCode:'M9',recordTag:'D',line:2}]);});
});

describe('pliego ~L records',()=>{
  it('appends L section text into expandedText while preserving existing T text',()=>{const source='~C|P1|u|Parent|1|x|0|\n~T|P1|Texto general|\n~L|P1|EJE\\Pliego de ejecucion material|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');const item=snapshot.items.find(x=>x.code==='P1');expect(item?.expandedText).toContain('Texto general');expect(item?.expandedText).toContain('EJE');expect(item?.expandedText).toContain('Pliego de ejecucion material');expect(snapshot.diagnostics).toEqual([]);});
  it('parses L records with extra trailing pipe separators cleanly',()=>{const source='~C|P2|u|Parent|1|x|0|\n~L|P2|MED\\Mediciones y abonos|||\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');const item=snapshot.items.find(x=>x.code==='P2');expect(item?.expandedText).toContain('MED');expect(item?.expandedText).toContain('Mediciones y abonos');expect(snapshot.diagnostics).toEqual([]);});
  it('reports unknown-parent for an L record without a matching concept',()=>{const source='~C|P3|u|Parent|1|x|0|\n~L|ZZZ|EJE\\Texto huérfano|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');expect(snapshot.diagnostics.filter(x=>x.code==='unknown-parent')).toMatchObject([{recordTag:'L',line:2}]);});
  it('reports a malformed L pair as a diagnostic instead of throwing',()=>{const source='~C|P4|u|Parent|1|x|0|\n~L|P4|EJETextoSinSeparador|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');const item=snapshot.items.find(x=>x.code==='P4');expect(item).toBeDefined();expect(snapshot.diagnostics.filter(x=>x.recordTag==='L')).toMatchObject([{code:'malformed-pliego',line:2}]);});
});

describe('source entity ~E records',()=>{
  it('parses an entity record into the snapshot without an unknown-tag diagnostic',()=>{const source='~E|PROV-01|Proveedor de Guadalajara|X-12345678|Guadalajara|Guadalajara|Calle 1|Contacto|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');expect(snapshot.entities).toMatchObject([{line:1,code:'PROV-01',name:'Proveedor de Guadalajara'}]);expect(snapshot.entities[0]?.fields).toEqual(['PROV-01','Proveedor de Guadalajara','X-12345678','Guadalajara','Guadalajara','Calle 1','Contacto','']);expect(snapshot.diagnostics).toEqual([]);});
  it('reports invalid-entity instead of unknown-tag for an entity record without a code',()=>{const source='~E||Entidad sin código|\n~E|   |Entidad con código en blanco|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');expect(snapshot.entities).toEqual([]);expect(snapshot.diagnostics).toMatchObject([{code:'invalid-entity',recordTag:'E',line:1},{code:'invalid-entity',recordTag:'E',line:2}]);});
  it('keeps an entity without a name as an empty name and preserves later records',()=>{const source='~E|PROV-02|\n~E|PROV-03|Tercero|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');expect(snapshot.entities).toMatchObject([{code:'PROV-02',name:''},{code:'PROV-03',name:'Tercero'}]);expect(snapshot.diagnostics).toEqual([]);});
});

describe('Synthetic Windows-1252 profile',()=>{it('parses a synthetic assembly with three complete ordered lines',()=>{const b=readFileSync('fixtures/bc3/synthetic-assembly.windows-1252.bc3');const s=parseBc3(b,'guadalajara-2016-eu','synthetic-assembly.windows-1252.bc3');const item=s.items.find(x=>x.code==='SYN-ASM-001');expect(item?.kind).toBe('partida');expect(item?.description).toBe('Synthetic assembly Ÿ');const lines=s.breakdowns.filter(x=>x.parent.codeKey==='syn-asm-001').map(x=>x.line);expect(lines.map(x=>x.component.code)).toEqual(['SYN-LAB-001','SYN-MAT-002','SYN-TOOL-003']);expect(lines.map(x=>({ordinal:x.ordinal,component:x.component,factor:x.factor,yield:x.yield}))).toEqual([{ordinal:0,component:{code:'SYN-LAB-001',kind:'resource',description:'Synthetic labor',unit:'h',unitPrice:'25'},factor:'1',yield:'0.5'},{ordinal:1,component:{code:'SYN-MAT-002',kind:'resource',description:'Synthetic material',unit:'kg',unitPrice:'3.5'},factor:'2',yield:'1.25'},{ordinal:2,component:{code:'SYN-TOOL-003',kind:'resource',description:'Synthetic tool',unit:'u',unitPrice:'12'},factor:'1',yield:'0.1'}]);});
  it('resolves hierarchy suffixes only as an exact-first fallback',()=>{const source='~C|A#|u|Parent|1|x|0|\n~C|A01#|u|Child|2|x|0|\n~D|A#|A01\\\\1\\\\1|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');expect(snapshot.items.some(x=>x.code==='A#')).toBe(true);expect(snapshot.breakdowns[0]?.line.component.code).toBe('A01#');});
  it('prefers exact children and rejects near matches',()=>{const source='~C|P#|u|Parent|1|x|0|\n~C|A01|u|Exact|2|x|0|\n~C|A01#|u|Suffixed|3|x|0|\n~D|P#|A01\\\\1\\\\1|\n~C|Q#|u|Parent|1|x|0|\n~D|Q#|A010\\\\1\\\\1|\n';const snapshot=parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','synthetic.bc3');expect(snapshot.breakdowns.find(x=>x.parent.codeKey==='p#')?.line.component.code).toBe('A01');expect(snapshot.diagnostics.some(x=>x.code==='unresolved-child'&&x.line===6)).toBe(true);});
  it('reports monotonic record processing with the actual record count before relation validation',()=>{const source='~C|A|u|A|1|x|0|\n~C|B|u|B|1|x|0|\n~D|A|B\\\\1\\\\1|\n';const progress:unknown[]=[];parseBc3(new TextEncoder().encode(source),'guadalajara-2016-eu','progress.bc3',(update)=>progress.push(update));expect(progress).toEqual([{stage:'processing-records',completed:1,total:3},{stage:'processing-records',completed:2,total:3},{stage:'processing-records',completed:3,total:3},{stage:'validating-relations'}]);});});
